name: Readings about Physics, Maths and Computer Science/Logic
markdown: redcarpet
pygments: true
paginate: 5
post:
  template: _post.txt
  extension: md
editor: ec
git:
  branch: master
baseurl: /phi-mu-lambda
